DeleteLostUinApplication:
   Prereg_DeleteLostUinApplication_All_Valid_Smoke_sid:
      endPoint: /preregistration/v1/applications/prereg/{applicationId}
      role: batch
      checkErrorsOnlyInResponse: true
      restMethod: delete
      inputTemplate: preReg/DeleteLostUinApplication/deleteLostUinApplication
      outputTemplate: preReg/DeleteLostUinApplication/deleteLostUinApplicationResult
      input: '{
  "applicationId": "$ID:CreatePrereg_Valid_Smoke_sid_preRegistrationId$"
}'
      output: '{
       "deletedBy": "$IGNORE$"
}'
   Prereg_DeleteLostUinApplication_after_its_deletion:
      endPoint: /preregistration/v1/applications/prereg/{applicationId}
      role: batch
      checkErrorsOnlyInResponse: true
      restMethod: delete
      inputTemplate: preReg/DeleteLostUinApplication/deleteLostUinApplication
      outputTemplate: preReg/error
      input: '{
  "applicationId": "$ID:CreatePrereg_Valid_Smoke_sid_preRegistrationId$"
}'
      output: '{
   "errors": [ 
    {
      "errorCode": "PRG_PAM_APP_005"
    }
  ]
}'
   Prereg_DeleteLostUinApplication_multiple_application_sid:
      endPoint: /preregistration/v1/applications/prereg/{applicationId}
      role: batch
      checkErrorsOnlyInResponse: true
      restMethod: delete
      inputTemplate: preReg/DeleteLostUinApplication/deleteLostUinApplication
      outputTemplate: preReg/DeleteLostUinApplication/deleteLostUinApplicationResult
      input: '{
  "applicationId": "$ID:CreatePrereg_All_Valid_Smoke_UpdateDocRefID_sid_preRegistrationId$"
}'
      output: '{
       "deletedBy": "$IGNORE$"
}'
   Prereg_DeleteLostUinApplication_inValid_preRegistrationId_sid:
      endPoint: /preregistration/v1/applications/prereg/{applicationId}
      role: batch
      restMethod: delete
      inputTemplate: preReg/DeleteLostUinApplication/deleteLostUinApplication
      outputTemplate: preReg/error
      input: '{
  "applicationId": "nhhh654443@@ffffv"
}'
      output: '{
   "errors": [ 
    {
      "errorCode": "PRG_PAM_APP_005"
    }
  ]
}'
   Prereg_DeleteLostUinApplication_random_number_sid:
      endPoint: /preregistration/v1/applications/prereg/{applicationId}
      role: batch
      restMethod: delete
      inputTemplate: preReg/DeleteLostUinApplication/deleteLostUinApplication
      outputTemplate: preReg/error
      input: '{
  "applicationId": "12736445738389"
}'
      output: '{
   "errors": [ 
    {
      "errorCode": "PRG_PAM_APP_005"
    }
  ]
}'